services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    command: >
      sh -c '
      if [ "$PRODUCTION" = "false" ]; then
        uvicorn app.main:app --host 0.0.0.0 --port ${APP_PORT} --reload;
      else
        uvicorn app.main:app --host 0.0.0.0 --port ${APP_PORT};
      fi'

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./backend:/app
    command: >
      sh -c '
      if [ "$PRODUCTION" = "false" ]; then
        watchmedo auto-restart --directory=./ --pattern="*.py" --recursive -- \
          celery -A app.worker.celery_app worker --loglevel=info --concurrency=2;
      else
        celery -A app.worker.celery_app worker --loglevel=info --concurrency=2;
      fi'
    depends_on:
      - redis

  flower:
    image: mher/flower
    env_file:
      - .env
    restart: unless-stopped
    command: >
      celery --broker=${CELERY_BROKER_URL} flower --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - worker

  redis:
    image: redis:latest

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - backend
