services:
  redis:
    image: redis:7
    restart: always
    networks:
      - backend_net

  backend:
    build: ./backend
    env_file:
      - .env
    restart: always
    user: "${UID}:${GID}"
    volumes:
      - ./backend:/app
    ports:
      - "${APP_PORT}:5000"
    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 5000
      --reload
    depends_on:
      - redis
    networks:
      - backend_net

  worker:
    build: ./backend
    env_file:
      - .env
    restart: always
    user: "${UID}:${GID}"
    volumes:
      - ./backend:/app
    command: >
      watchmedo auto-restart
      --directory=./
      --pattern="*.py"
      --recursive --
      celery -A app.celery_app worker
      --loglevel=info
      --concurrency=2
    depends_on:
      - redis
    networks:
      - backend_net

  flower:
    image: mher/flower
    env_file:
      - .env
    restart: unless-stopped
    command: >
      celery --broker=${CELERY_BROKER_URL} flower --port=5555
    ports:
      - "${FLOWER_PORT}:5555"
    depends_on:
      - worker
    networks:
      - backend_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "${FRONT_PORT}:3000"
    command: npm run dev

networks:
  backend_net:
