services:
  redis:
    image: redis:7
    restart: unless-stopped
    networks:
      - backend_net

  backend:
    image: hsekhalilian/my-images:celery-fastapi-boilerplate-backend-latest
    env_file:
      - .env
      - backend/.env
    ports:
      - "${APP_PORT}:5000"
    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 5000
      --workers 4
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - backend_net

  worker:
    image: hsekhalilian/my-images:celery-fastapi-boilerplate-backend-latest
    env_file:
      - .env
      - backend/.env
    command: >
      celery -A app.celery_app worker
      --loglevel=info
      --concurrency=4
      --queues=celery
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - backend_net

  webhook-worker:
    image: hsekhalilian/my-images:celery-fastapi-boilerplate-backend-latest
    env_file:
      - .env
      - backend/.env
    command: >
      celery -A app.celery_app worker
      --loglevel=info
      --concurrency=2
      --queues=webhooks
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - backend_net

  flower:
    image: mher/flower
    env_file:
      - .env
      - backend/.env
    restart: unless-stopped
    command: >
      celery --broker=${CELERY_BROKER_URL} flower --port=5555
    ports:
      - "${FLOWER_PORT}:5555"
    depends_on:
      - worker
      - webhook-worker
    networks:
      - backend_net

  frontend:
    image: hsekhalilian/my-images:celery-fastapi-boilerplate-frontend-latest
    env_file:
      - .env
    ports:
      - "${FRONT_PORT}:3000"
    restart: unless-stopped
    networks:
      - backend_net

networks:
  backend_net:
